begin;

create table if not exists public.submission_attempts (
  id bigint generated by default as identity primary key,
  request_id uuid not null default gen_random_uuid(),
  audience text check (audience in ('candidate', 'employer')),
  ip_hash text not null,
  contact_hash text,
  outcome text not null check (
    outcome in ('accepted', 'captcha_failed', 'rate_limited', 'validation_failed', 'server_failed')
  ),
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists submission_attempts_ip_created_idx
  on public.submission_attempts (ip_hash, created_at desc);

create index if not exists submission_attempts_contact_created_idx
  on public.submission_attempts (contact_hash, created_at desc)
  where contact_hash is not null;

create index if not exists submission_attempts_created_idx
  on public.submission_attempts (created_at desc);

alter table public.submission_attempts enable row level security;

revoke all on table public.submission_attempts from anon, authenticated;
grant all on table public.submission_attempts to service_role;

drop policy if exists "HR team can read submission attempts" on public.submission_attempts;
create policy "HR team can read submission attempts"
on public.submission_attempts
for select
to authenticated
using (
  (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

grant select on table public.submission_attempts to authenticated;

create or replace function public.cleanup_submission_attempts(retention_days integer default 30)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count bigint;
begin
  if retention_days < 1 or retention_days > 365 then
    raise exception 'retention_days must be between 1 and 365';
  end if;

  delete from public.submission_attempts
  where created_at < now() - make_interval(days => retention_days);

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

revoke all on function public.cleanup_submission_attempts(integer) from public, anon, authenticated;
grant execute on function public.cleanup_submission_attempts(integer) to service_role;

comment on table public.submission_attempts is
  'Privacy-preserving anti-abuse log. Raw IP addresses and contact values are never stored.';

comment on column public.submission_attempts.ip_hash is
  'SHA-256 hash of normalized IP plus a server-only pepper.';

comment on column public.submission_attempts.contact_hash is
  'SHA-256 hash of normalized email/phone plus a server-only pepper.';

commit;
